language: node_js
node_js:
  - "10"
sudo: true

addons:
  chrome: stable    
  
branches:
  only:
    - master

before_install:
  - cd LinkingYou
  
before_script:
  - npm install -g @angular/cli

script:
  - ng test --no-watch --code-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
