language: node_js
node_js:
  - "10"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules
    
before_install:
  - cd LinkingYou

addons:
  chrome: stable

script:
  - npm run lint
  - npm run test:headless
  - npm run build

after_success:
  - bash <(curl -s https://codecov.io/bash)
